### ISSUE TITLE
Style auto import dosen't work

### ISSUE THREAD

**Issue by wildseeder** [arco-design/arco-webpack-plugin#1]
Create an app with CRA:

```bash
npx create-react-app demo
cd demo
yarn eject
```

Install arco design and the plugin:

```bash
yarn add @arco-design/web-react
yarn add -D @arco-design/webpack-plugin
```

Modify  `config/webpack.config.js` to add the plugin:

```js
...
const ArcoWebpackPlugin = require('@arco-design/webpack-plugin');
...
module.exports = function (webpackEnv) {
  ...
  return {
    ...
    plugins: [
      ...
      new ArcoWebpackPlugin(),
    ].filter(Boolean),
    ...
  };
};
```

Change `src/App.js` content to:

```tsx
import { Button } from '@arco-design/web-react';

function App() {
  return (
    <Button>Button</Button>
  );
}

export default App;
```

Run with `yarn start`, it seems that style auto import dosen't work:

![20211030210034](https://user-images.githubusercontent.com/46044672/139533791-cd375420-fc56-4165-a659-5cea564b901a.png)

**Comment by kirazxyun** [comment]
@wildseeder Hello, in order to help you solve the problem faster, please provide a minimal project to reproduce the problem。

**Comment by wildseeder** [comment]
> @wildseeder Hello, in order to help you solve the problem faster, please provide a minimal project to reproduce the problem。

@kirazxyun the repo following steps above: https://github.com/wildseeder/arco-webpack-plugin-style-issue

**Comment by kirazxyun** [comment]
> > @wildseeder Hello, in order to help you solve the problem faster, please provide a minimal project to reproduce the problem。
> 
> @kirazxyun the repo following steps above: https://github.com/wildseeder/arco-webpack-plugin-style-issue

Sorry to reply you so late.  You need support the CSS preprocessor  `less` in your project.

**Comment by wildseeder** [comment]
> Sorry to reply you so late. You need support the CSS preprocessor `less` in your project.

@kirazxyun Thanks for your answer, it would be nice to have the corresponding description in the documentation.
